export interface BasemapOption {
  id: string;
  name: string;
  provider: "google" | "esri" | "osm";
  type: string;
  url: string;
  attribution: string;
  maxZoom: number;
  maxNativeZoom?: number;
  subdomains?: string[];
  description: string;
  previewColor: string;
}

export const BASEMAP_OPTIONS: BasemapOption[] = [
  {
    id: "google-hybrid",
    name: "Google Satelit Hybrid",
    provider: "google",
    type: "Satelit + Label",
    url: "https://mt{s}.google.com/vt/lyrs=y&x={x}&y={y}&z={z}",
    attribution: "&copy; Google Maps",
    maxZoom: 21,
    maxNativeZoom: 20,
    subdomains: ["0", "1", "2", "3"],
    description: "Citra satelit Google terbaru resolusi tinggi dengan label nama jalan.",
    previewColor: "#10b981",
  },
  {
    id: "google-satellite",
    name: "Google Satelit Murni",
    provider: "google",
    type: "Foto Satelit",
    url: "https://mt{s}.google.com/vt/lyrs=s&x={x}&y={y}&z={z}",
    attribution: "&copy; Google Maps",
    maxZoom: 21,
    maxNativeZoom: 20,
    subdomains: ["0", "1", "2", "3"],
    description: "Citra foto satelit terkini resolusi ultra tinggi tanpa label.",
    previewColor: "#059669",
  },
  {
    id: "google-terrain",
    name: "Google Terrain & Relief",
    provider: "google",
    type: "Relief",
    url: "https://mt{s}.google.com/vt/lyrs=p&x={x}&y={y}&z={z}",
    attribution: "&copy; Google Maps",
    maxZoom: 20,
    maxNativeZoom: 18,
    subdomains: ["0", "1", "2", "3"],
    description: "Peta topografi elevasi 3D dan bentuk relief fisik permukaan bumi.",
    previewColor: "#d97706",
  },
  {
    id: "google-streets",
    name: "Google Maps Jalan",
    provider: "google",
    type: "Jalan",
    url: "https://mt{s}.google.com/vt/lyrs=m&x={x}&y={y}&z={z}",
    attribution: "&copy; Google Maps",
    maxZoom: 21,
    maxNativeZoom: 20,
    subdomains: ["0", "1", "2", "3"],
    description: "Peta jalan resmi navigasi Google Maps paling mutakhir.",
    previewColor: "#0284c7",
  },
  {
    id: "esri-satellite",
    name: "Citra Satelit ESRI",
    provider: "esri",
    type: "Foto Satelit",
    url: "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",
    attribution: "Tiles &copy; Esri, Maxar, Earthstar Geographics",
    maxZoom: 20,
    maxNativeZoom: 19,
    description: "Citra satelit global resolusi tinggi dari ArcGIS ESRI.",
    previewColor: "#2563eb",
  },
  {
    id: "esri-streets",
    name: "ESRI Street Map",
    provider: "esri",
    type: "Jalan",
    url: "https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}",
    attribution: "Tiles &copy; Esri",
    maxZoom: 20,
    maxNativeZoom: 19,
    description: "Peta jalan kartografi jelas dengan rute jalan raya.",
    previewColor: "#0ea5e9",
  },
  {
    id: "esri-topo",
    name: "ESRI Topografi",
    provider: "esri",
    type: "Topografi",
    url: "https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}",
    attribution: "Tiles &copy; Esri",
    maxZoom: 20,
    maxNativeZoom: 19,
    description: "Peta kontur elevasi bumi dengan bayangan relief.",
    previewColor: "#84cc16",
  },
  {
    id: "esri-natgeo",
    name: "National Geographic",
    provider: "esri",
    type: "Kartografi",
    url: "https://server.arcgisonline.com/ArcGIS/rest/services/NatGeo_World_Map/MapServer/tile/{z}/{y}/{x}",
    attribution: "Tiles &copy; NatGeo & Esri",
    maxZoom: 17,
    maxNativeZoom: 16,
    description: "Gaya peta klasik National Geographic yang artistik.",
    previewColor: "#eab308",
  },
  {
    id: "osm-standard",
    name: "OpenStreetMap Standar",
    provider: "osm",
    type: "Jalan",
    url: "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
    attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
    maxZoom: 20,
    maxNativeZoom: 19,
    subdomains: ["a", "b", "c"],
    description: "Peta jalan global resmi berbasis kontribusi komunitas terkini.",
    previewColor: "#16a34a",
  },
  {
    id: "osm-hot",
    name: "OSM Humanitarian (HOT)",
    provider: "osm",
    type: "Fasilitas",
    url: "https://{s}.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png",
    attribution: '&copy; OpenStreetMap contributors, Humanitarian OpenStreetMap Team',
    maxZoom: 20,
    maxNativeZoom: 19,
    subdomains: ["a", "b", "c"],
    description: "Peta kemanusiaan dengan fokus fasilitas umum dan pemukiman.",
    previewColor: "#e11d48",
  },
  {
    id: "opentopomap",
    name: "OpenTopoMap Kontur",
    provider: "osm",
    type: "Relief",
    url: "https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png",
    attribution: '&copy; <a href="https://opentopomap.org">OpenTopoMap</a>',
    maxZoom: 18,
    maxNativeZoom: 17,
    subdomains: ["a", "b", "c"],
    description: "Garis kontur ketinggian dan bukit/lembah detail.",
    previewColor: "#0d9488",
  },
  {
    id: "cyclosm",
    name: "CyclOSM Jalur Sepeda",
    provider: "osm",
    type: "Navigasi",
    url: "https://{s}.tile-cyclosm.openstreetmap.fr/cyclosm/{z}/{x}/{y}.png",
    attribution: '&copy; <a href="https://www.cyclosm.org">CyclOSM</a>',
    maxZoom: 19,
    maxNativeZoom: 18,
    subdomains: ["a", "b", "c"],
    description: "Peta navigasi rute sepeda dan jalur terbuka.",
    previewColor: "#8b5cf6",
  },
];
